---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - openldap

- include: client.yml
  when: "'client' in openldap_roles"
  tags:
    - openldap
    - openldap_client

- include: server.yml
  when: "'server' in openldap_roles"
  tags:
    - openldap
    - openldap_client
    - openldap_users
