---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - logstash

- include: config.yml
  tags:
    - logstash
    - logstash_config

- include: ssl.yml
  tags:
    - logstash
    - logstash_ssl

- include: plugins.yml
  tags:
    - logstash
    - logstash_plugins

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: yes
  tags:
    - logstash
