---
- name: Ensure that Thrift build dependencies are satisfied
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ant
    - boost-devel
    - flex
    - gcc-c++
    - libevent-devel
    - libtool
    - lua-devel
    - make
    - openssl-devel
    - pkgconfig
    - python-devel
    - zlib-devel
