---
- name: Ensure that all VPCs are provisioned
  include: ensure_vpc_provisioned.yml
  with_items: "{{ spine_vpcs_order }}"
  loop_control:
    loop_var: spine_cur_vpc_name
  tags:
    - provision_spine_dc
    - provision_spine_dc_env

- name: Ensure that all created VPCs are properly linked
  include: ensure_vpc_peered.yml
  with_items: "{{ spine_vpcs_order }}"
  loop_control:
    loop_var: spine_cur_vpc_name
  tags:
    - provision_spine_dc
    - provision_spine_dc_env

- name: Ensure that all VPC routing tables are created
  include: ensure_vpc_route_tables.yml
  with_items: "{{ spine_vpcs_order }}"
  loop_control:
    loop_var: spine_cur_vpc_name
  tags:
    - provision_spine_dc
    - provision_spine_dc_env

- name: Ensure that all Route53 zones are created
  debug:
    var: spine_cur_route53_zone
  with_items: "{{ spine_route53_zones }}"
  loop_control:
    loop_var: spine_cur_route53_zone
  tags:
    - provision_spine_dc_route53

- name: Ensure that all Route53 zones are created
  include: ensure_route53_zone_created.yml
  with_items: "{{ spine_route53_zones }}"
  loop_control:
    loop_var: spine_cur_route53_zone
  tags:
    - provision_spine_dc
    - provision_spine_dc_env
    - provision_spine_dc_route53
