---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - automake

- name: Download automake release tarball
  get_url:
    url: "{{ automake_gnu_mirror_base }}/automake/automake-{{ automake_version }}.tar.gz"
    dest: "{{ automake_source_dir }}/automake-{{ automake_version }}.tar.gz"
  register: automake_download
  tags:
    - automake

- name: Untar automake tarball
  command: "tar xvf automake-{{ automake_version }}.tar.gz"
  args:
    chdir: "{{ automake_source_dir }}"
  when: automake_download.changed
  tags:
    - automake

- name: Configure automake build
  command: "./configure --prefix={{ automake_install_dir }}"
  args:
    chdir: "{{ automake_source_dir }}/automake-{{ automake_version }}"
  when: automake_download.changed
  tags:
    - automake

- name: Build automake
  command: make
  args:
    chdir: "{{ automake_source_dir }}/automake-{{ automake_version }}"
  when: automake_download.changed
  tags:
    - automake

- name: Install automake
  command: "paco -lp automake-{{ automake_version }} -- make install"
  args:
    chdir: "{{ automake_source_dir }}/automake-{{ automake_version }}"
  when: automake_download.changed
  tags:
    - automake
